---
- name: install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: run nginx
  service:
    name: nginx
    state: started

- lineinfile:
    path: '/etc/nginx/nginx.conf'
    regexp: 'listen'
    insertafter: 'listen'
    line: 'listen 8080'
    state: absent

- name: restart nginx
  service:
    name: nginx
    state: restarted
